theme: jekyll-theme-minimal
title: 'Statistical Insights: Applying Inferential Analysis to Software Incident Data'
description: White paper that explores using Statistics to analyze Software Incident Data
